import fs from 'node:fs';
import path from 'node:path';
import { loadMenu, loadProviders, expandAnswers, resolve } from './resolver.mjs';

const VERSION = '0.1.0';

function write(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

export function compile(rawAnswers, outDir) {
  const menu = loadMenu();
  const providers = loadProviders();
  const answers = expandAnswers(rawAnswers, menu);
  const result = resolve(answers, providers);
  const { flags, providers: sel, labels } = answers;
  const root = path.resolve(outDir);

  // ---- context files ----
  write(path.join(root, '.callsmith/context/architecture.md'), renderArchitecture(result, flags, sel, labels));
  write(path.join(root, '.callsmith/context/audio-contract.md'), renderAudioContract(result));
  write(path.join(root, '.callsmith/context/potholes.md'), renderPotholes(result));
  write(path.join(root, '.callsmith/context/build-order.md'), renderBuildOrder(result, sel, flags));

  // ---- .env.example ----
  write(path.join(root, '.env.example'),
    '# Callsmith-generated environment template.\n' +
    result.envKeys.map(k => `${k}=`).join('\n') + '\n');

  // ---- lock ----
  const lock = {
    callsmith_version: VERSION,
    architecture: { ...flags },
    providers: Object.fromEntries(Object.entries(sel).map(([k, v]) => [k, v.id])),
    provider_models: result.pipeline.filter(p => p.id).map(p => {
      const pk = providers[p.id] || {};
      return { role: p.role, id: p.id, model: pk.model || null };
    }),
    compatibility: {
      requires_custom_bridge: result.transforms.length > 0,
      transform_count: result.transforms.length,
      blockers: result.blockers.length,
    },
  };
  write(path.join(root, 'callsmith.lock.json'), JSON.stringify(lock, null, 2) + '\n');

  // ---- recipe (the handoff packet) ----
  write(path.join(root, 'callsmith.recipe.md'), renderRecipe(result, flags, sel, labels, lock));

  return { lock, result, files: [
    'callsmith.recipe.md', 'callsmith.lock.json', '.env.example',
    '.callsmith/context/architecture.md', '.callsmith/context/audio-contract.md',
    '.callsmith/context/potholes.md', '.callsmith/context/build-order.md',
  ] };
}

function stackLine(labels, key, fallback) { return labels[key] || fallback || '—'; }

function renderRecipe(result, flags, sel, labels, lock) {
  const { transforms, blockers, notes, potholes } = result;
  const needsBridge = transforms.length > 0;
  const lines = [];
  lines.push(`# Callsmith Recipe`);
  lines.push('');
  lines.push(`A compiled implementation contract for a ${stackLine(labels,'business_logic','voice')} agent.`);
  lines.push(`Generated by callsmith v${VERSION}. Reproduce from \`callsmith.lock.json\`.`);
  lines.push('');
  lines.push('## Intent');
  lines.push('');
  lines.push(`- **Surface:** ${stackLine(labels,'surface')}`);
  lines.push(`- **Architecture:** ${stackLine(labels,'architecture')}`);
  lines.push(`- **Direction:** ${flags.direction || 'n/a'}`);
  lines.push(`- **Language:** ${flags.language || 'en'}`);
  lines.push(`- **Barge-in:** ${flags.barge_in}`);
  lines.push(`- **Latency priority:** ${flags.latency}`);
  lines.push(`- **Job:** ${stackLine(labels,'business_logic')}`);
  lines.push(`- **Tools:** ${flags.tools}`);
  lines.push(`- **Deployment:** ${stackLine(labels,'deployment')}`);
  lines.push('');
  lines.push('## Selected stack');
  lines.push('');
  for (const p of result.pipeline) lines.push(`- **${p.role}:** ${p.label || p.id}`);
  lines.push('');
  lines.push('## Audio contract (read this before writing any audio code)');
  lines.push('');
  if (needsBridge) {
    lines.push('> **A custom audio bridge is required.** Do not pass telephony frames into the model directly.');
    lines.push('');
    for (const t of transforms) lines.push(`- [${t.direction}] ${t.step}  (${t.from} -> ${t.to})`);
    lines.push('');
    lines.push('Full contract: see [.callsmith/context/audio-contract.md](.callsmith/context/audio-contract.md).');
  } else {
    lines.push('> **No custom transcoding in your code** — normalization is handled by a native layer.');
    lines.push('');
    for (const n of notes) lines.push(`- ${n}`);
  }
  lines.push('');
  lines.push('## Blockers & potholes');
  lines.push('');
  if (blockers.length === 0 && potholes.filter(p => p.severity === 'blocker').length === 0) {
    lines.push('No blockers detected for this stack. Review warnings in [.callsmith/context/potholes.md](.callsmith/context/potholes.md).');
  } else {
    for (const b of blockers) lines.push(`- **[BLOCKER]** ${b.note}`);
    for (const p of potholes.filter(p => p.severity === 'blocker')) lines.push(`- **[BLOCKER / ${p.source}]** ${p.note}`);
  }
  lines.push('');
  lines.push('## Build order (follow in sequence)');
  lines.push('');
  lines.push('See [.callsmith/context/build-order.md](.callsmith/context/build-order.md). Do not skip the audio-contract step.');
  lines.push('');
  lines.push('## Required docs');
  lines.push('');
  lines.push('Hydrate provider docs before coding:');
  lines.push('```bash');
  lines.push('callsmith docs   # fetches fresh slices into .callsmith/docs/');
  lines.push('```');
  lines.push('');
  lines.push('## Agent instructions');
  lines.push('');
  lines.push('Before writing code, read these files in order:');
  lines.push('1. `.callsmith/context/architecture.md`');
  lines.push('2. `.callsmith/context/audio-contract.md`');
  lines.push('3. `.callsmith/context/potholes.md`');
  lines.push('4. `.callsmith/context/build-order.md`');
  lines.push('');
  lines.push('Do not invent unsupported audio formats. Do not skip transcoding if the audio-contract requires it. Do not assume telephony frame boundaries align with model frames.');
  lines.push('');
  return lines.join('\n');
}

function renderArchitecture(result, flags, sel, labels) {
  const L = [];
  L.push('# Architecture');
  L.push('');
  L.push('## Pipeline');
  for (const p of result.pipeline) L.push(`1. **${p.role}** — ${p.label || p.id}`);
  L.push('');
  L.push('## Flags');
  for (const [k, v] of Object.entries(flags)) L.push(`- ${k}: ${v}`);
  return L.join('\n') + '\n';
}

function renderAudioContract(result) {
  const L = [];
  L.push('# Audio Contract');
  L.push('');
  L.push('This file is the single source of truth for what audio conversions the implementation must perform.');
  L.push('');
  if (result.transforms.length === 0) {
    L.push('**No custom transcoding required.** Selected native layer absorbs it:');
    L.push('');
    for (const n of result.notes) L.push(`- ${n}`);
  } else {
    L.push('## Required transforms');
    L.push('');
    L.push('| Direction | Step | From | To |');
    L.push('|---|---|---|---|');
    for (const t of result.transforms) L.push(`| ${t.direction} | ${t.step} | ${t.from} | ${t.to} |`);
    L.push('');
    L.push('## Implementation notes');
    L.push('');
    L.push('- Reassemble telephony frames by byte budget, not message boundary, before resampling.');
    L.push('- Use two independent resamplers if input/output rates differ.');
    L.push('- On interruption, flush the outbound buffer before the next model chunk.');
  }
  return L.join('\n') + '\n';
}

function renderPotholes(result) {
  const L = ['# Potholes', ''];
  const order = ['blocker', 'warning', 'note'];
  for (const sev of order) {
    const items = result.potholes.filter(p => p.severity === sev);
    if (!items.length) continue;
    L.push(`## ${sev}`);
    for (const p of items) L.push(`- **[${p.source}]** ${p.note}`);
    L.push('');
  }
  return L.join('\n') + '\n';
}

function renderBuildOrder(result, sel, flags) {
  const L = ['# Build Order', '', 'Implement top-to-bottom. Verify each step before the next.', ''];
  L.push('1. **Config & env** — load keys from `.env.example`; validate presence at startup.');
  L.push('2. **Session lifecycle state machine** — map provider events to a single session model (call_started, media_active, interruption, ended).');
  if (result.transforms.length > 0) {
    L.push('3. **Audio bridge** — implement every transform in `.callsmith/context/audio-contract.md`. Add a fake audio-frame test that round-trips a known sample.');
  } else {
    L.push('3. **Audio wiring** — connect the native-normalized PCM streams; confirm frame format matches the model ingest contract.');
  }
  L.push('4. **Model session** — connect realtime/STT+LLM+TTS; wire interruption handling.');
  L.push('5. **Business logic & tools** — implement the job and tool calls.');
  L.push('6. **Observability** — log inbound, post-transcode, model output, and outbound streams separately.');
  L.push('7. **E2E test** — fake call simulator covering call lifecycle + barge-in.');
  return L.join('\n') + '\n';
}
